import { useState } from "react"
import { useQuery } from "@tanstack/react-query"
import { AlertTriangle, ArrowLeft, Building2, CalendarRange, Download, ExternalLink, FileCheck2, UserRound } from "lucide-react"
import { Link, useParams } from "react-router"
import { toast } from "sonner"
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Skeleton } from "@/components/ui/skeleton"
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table"
import { serviceOrdersApi } from "@/features/service-orders/service-orders.api"

const money = (value: string) => new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" }).format(Number(value))
const quantity = (value: string) => new Intl.NumberFormat("pt-BR", { maximumFractionDigits: 2 }).format(Number(value))
const date = (value: string | null) => value ? new Intl.DateTimeFormat("pt-BR", { dateStyle: "medium" }).format(new Date(value)) : "Não informado"

export function ServiceOrderDetailsPage() {
  const { serviceOrderId = "" } = useParams()
  const [loading, setLoading] = useState<"html" | "pdf" | null>(null)
  const query = useQuery({ queryKey: ["service-orders", "details", serviceOrderId], queryFn: () => serviceOrdersApi.details(serviceOrderId), enabled: Boolean(serviceOrderId) })
  const document = async (format: "html" | "pdf") => { const win = format === "html" ? window.open("", "_blank") : null; setLoading(format); try { const blob = await serviceOrdersApi.document(serviceOrderId, format); const url = URL.createObjectURL(blob); if (win) win.location.href = url; else { const a = window.document.createElement("a"); a.href = url; a.download = `ordem-servico-${query.data?.serviceOrderNumber}.${format}`; a.click() } window.setTimeout(() => URL.revokeObjectURL(url), 60_000) } catch (error) { win?.close(); toast.error(error instanceof Error ? error.message : "Erro ao gerar documento.") } finally { setLoading(null) } }
  if (query.isLoading) return <div className="space-y-4">{Array.from({ length: 5 }).map((_, i) => <Skeleton key={i} className="h-28" />)}</div>
  if (query.isError || !query.data) return <div className="space-y-4"><Button asChild variant="ghost"><Link to="/service-orders"><ArrowLeft className="size-4" />Voltar</Link></Button><Alert variant="destructive"><AlertTriangle /><AlertTitle>Não foi possível carregar a OS</AlertTitle><AlertDescription>{query.error?.message}</AlertDescription></Alert></div>
  const order = query.data
  return <div className="space-y-6"><div><Button asChild variant="ghost" className="mb-3 -ml-3"><Link to="/service-orders"><ArrowLeft className="size-4" />Voltar às OS</Link></Button><div className="flex flex-col justify-between gap-4 lg:flex-row lg:items-end"><div><div className="mb-3 flex gap-2"><Badge>{order.serviceOrderNumber}</Badge>{order.isEmergency && <Badge variant="destructive">Emergencial</Badge>}</div><h1 className="text-3xl font-semibold">Ordem de Serviço</h1><p className="mt-2 text-sm text-muted-foreground">Emitida em {date(order.issuedAt)} · NE {order.commitmentNoteNumber}</p></div><div className="flex gap-2"><Button variant="outline" disabled={Boolean(loading)} onClick={() => document("html")}><ExternalLink className="size-4" />Visualizar</Button><Button disabled={Boolean(loading)} onClick={() => document("pdf")}><Download className="size-4" />Baixar PDF</Button></div></div></div>
    <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><Card className="border-none shadow-sm"><CardContent className="p-5"><FileCheck2 className="size-5 text-primary" /><p className="mt-3 text-xs text-muted-foreground">Valor da OS</p><p className="mt-1 text-xl font-semibold">{money(order.totalAmount)}</p></CardContent></Card><Card className="border-none shadow-sm"><CardContent className="p-5"><Building2 className="size-5 text-primary" /><p className="mt-3 text-xs text-muted-foreground">Contratada</p><p className="mt-1 font-semibold">{order.contractorName}</p><p className="text-xs text-muted-foreground">{order.contractorCnpj}</p></CardContent></Card><Card className="border-none shadow-sm"><CardContent className="p-5"><UserRound className="size-5 text-primary" /><p className="mt-3 text-xs text-muted-foreground">Fiscal/requisitante</p><p className="mt-1 font-semibold">{order.requesterRank} {order.requesterName}</p></CardContent></Card><Card className="border-none shadow-sm"><CardContent className="p-5"><CalendarRange className="size-5 text-primary" /><p className="mt-3 text-xs text-muted-foreground">Execução planejada</p><p className="mt-1 font-semibold">{date(order.plannedStartDate)} — {date(order.plannedEndDate)}</p></CardContent></Card></div>
    <Card className="border-none shadow-sm"><CardHeader><CardTitle>Vínculos e execução</CardTitle></CardHeader><CardContent className="grid gap-5 sm:grid-cols-2 lg:grid-cols-4"><div><p className="text-xs text-muted-foreground">Projeto</p><Button asChild variant="link" className="h-auto p-0"><Link to={`/projects/${order.project.id}`}>PRJ-{order.project.projectCode}</Link></Button></div><div><p className="text-xs text-muted-foreground">Estimativa</p><p className="font-medium">EST-{order.estimate.estimateCode}</p></div><div><p className="text-xs text-muted-foreground">DIEx</p><p className="font-medium">{order.diexRequest?.diexNumber ?? "Não vinculado"}</p></div><div><p className="text-xs text-muted-foreground">Local</p><p className="font-medium">{order.executionLocation ?? "Não informado"}</p></div></CardContent></Card>
    <Card className="border-none shadow-sm"><CardHeader><CardTitle>Itens ordenados</CardTitle></CardHeader><CardContent><Table><TableHeader><TableRow><TableHead>Código</TableHead><TableHead>Descrição</TableHead><TableHead>Unidade</TableHead><TableHead>Quantidade</TableHead><TableHead>Valor unitário</TableHead><TableHead className="text-right">Total</TableHead></TableRow></TableHeader><TableBody>{order.items.map((item) => <TableRow key={item.id}><TableCell className="font-medium">{item.itemCode}</TableCell><TableCell>{item.description}</TableCell><TableCell>{item.supplyUnit}</TableCell><TableCell>{quantity(item.quantityOrdered)}</TableCell><TableCell>{money(item.unitPrice)}</TableCell><TableCell className="text-right font-semibold">{money(item.totalPrice)}</TableCell></TableRow>)}</TableBody></Table></CardContent></Card>
  </div>
}
