import { useQuery } from "@tanstack/react-query"
import { api } from "@/lib/api"
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog"
import { financialStatusLabel, formatNeDate, formatNeMoney } from "../portfolio-presentation"
import { attendedOmLabel } from "./attended-om-select"
import type { MilitaryOrganization } from "@/features/projects/projects.types"

type Json = Record<string, unknown>
type Financial = { current: number | null; liquidated: number | null; paid: number | null; issuedAt?: string | null; liquidatedAt?: string | null; paidAt?: string | null; creditNotes?: string[]; paidNet?: number | null; deductions?: number | null; status: string; incomplete?: boolean; inconsistent?: boolean; liquidationIncomplete?: boolean; paymentIncomplete?: boolean; unresolvedLiquidations?: number; unresolvedPayments?: number }
type Snapshot = { document: unknown; related: unknown; fetchedAt?: string; financial?: { version?: number; liquidatedComplete?: boolean; paidComplete?: boolean; documents: Array<{ code: string; phase: number; amount: number | null; error?: string; subitems: Json[] }> } }
type Archive = { snapshot: Snapshot; financial: Financial; attendedOm: MilitaryOrganization | null; observation: string | null; updatedAt: string }
type ProjectNote = { currentAmount: number; liquidatedAmount: number; paidAmount: number; issuedAt: string | null; creditNotes?: string[]; financialStatus: string; syncStatus: string; rawSnapshot: unknown; lastSyncAt: string; documents: Array<{ number: string; phase: string; amount: number; issuedAt: string; rawSnapshot: unknown }>; invoices: Array<{ id: string; number: string; series: string | null; issuedAt: string; grossAmount: number; supplierCnpj: string; issuerName: string | null; source: "MANUAL" | "XML"; conferenceStatus: "PENDING" | "CONFERRED" | "DIVERGENT"; xmlChecksumSha256: string | null; itemCount: number | null }> }
export type NeDetailSelection = { externalCode: string; number: string; noteId?: string | null }
export function NeFinancialDetailDialog({ selection, onClose }: { selection: NeDetailSelection | null; onClose: () => void }) {
  const query = useQuery({
    queryKey: ["financial-execution", "saved-ne-detail", selection?.noteId ?? selection?.externalCode], enabled: Boolean(selection), retry: false,
    queryFn: async () => {
      if (selection?.noteId) {
        const note = await api.get<ProjectNote>(`/financial-execution/commitment-notes/${encodeURIComponent(selection.noteId)}`)
        const latestDate = (phase: string) => note.documents.filter(document => document.phase === phase).map(document => document.issuedAt).sort().at(-1) ?? null
        return { financial: { current: note.currentAmount, liquidated: note.liquidatedAmount, paid: note.paidAmount, issuedAt: note.issuedAt, liquidatedAt: latestDate("LIQUIDACAO"), paidAt: latestDate("PAGAMENTO"), creditNotes: note.creditNotes ?? [], status: note.syncStatus === "VALIDADO" ? note.financialStatus : "A_CONFERIR", inconsistent: note.syncStatus === "DIVERGENTE" || note.paidAmount > note.currentAmount + 0.01 || note.paidAmount > note.liquidatedAmount + 0.01 || note.liquidatedAmount > note.currentAmount + 0.01 || [note.currentAmount, note.liquidatedAmount, note.paidAmount].some(value => value < 0) }, attendedOm: null, observation: null, updatedAt: note.lastSyncAt, invoices: note.invoices, snapshot: { document: note.rawSnapshot, related: note.documents } } as Archive & { invoices: ProjectNote["invoices"] }
      }
      return api.get<Archive>(`/financial-execution/discovery/archive/${encodeURIComponent(selection!.externalCode)}`)
    },
  })
  const result = query.data
  return <Dialog open={Boolean(selection)} onOpenChange={open => { if (!open) onClose() }}><DialogContent className="max-h-[85vh] overflow-auto sm:max-w-4xl"><DialogHeader><DialogTitle>Nota de Empenho {selection?.number}</DialogTitle><DialogDescription>Informações salvas no SAGEP · {selection?.externalCode}</DialogDescription></DialogHeader>
    {query.isLoading && <p>Carregando informações da NE…</p>}
    {query.isError && <p role="alert">Não foi possível abrir a NE: {query.error.message}</p>}
    {result && <>
      <p className="font-semibold">Situação: {financialStatusLabel(result.financial.inconsistent ? "DIVERGENTE" : result.financial.status)}</p>
      <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><div className="rounded border p-3"><p className="text-sm text-muted-foreground">Data de emissão</p><p className="font-semibold">{formatNeDate(result.financial.issuedAt)}</p></div><div className="rounded border p-3"><p className="text-sm text-muted-foreground">NC referenciada</p><p className="font-semibold">{result.financial.creditNotes?.length ? result.financial.creditNotes.join(", ") : "Não localizada nos dados oficiais"}</p></div><div className="rounded border p-3"><p className="text-sm text-muted-foreground">OM atendida</p><p className="font-semibold">{attendedOmLabel(result.attendedOm)}</p></div><div className="rounded border p-3"><p className="text-sm text-muted-foreground">Observação</p><p className="font-semibold">{result.observation || "Não informada"}</p></div></div>
      <div className="grid gap-3 sm:grid-cols-3">{[["Empenhado", "Data do empenho", result.financial.current, result.financial.issuedAt], ["Liquidado", "Data da liquidação", result.financial.liquidated, result.financial.liquidatedAt], ["Pago", "Data do pagamento", result.financial.paid, result.financial.paidAt]].map(([label, dateLabel, value, actionDate]) => <div key={String(label)} className="rounded border p-3"><p className="text-sm text-muted-foreground">{label}</p><p className="text-xl font-semibold">{formatNeMoney(value as number | null)}</p><p className="mt-1 text-xs text-muted-foreground">{dateLabel}: {formatNeDate(actionDate as string | null)}</p></div>)}</div>
      {(result.financial.deductions ?? 0) > 0 && <p className="rounded border p-3 text-sm">Composição do pagamento: {formatNeMoney(result.financial.paidNet ?? null)} repassados ao fornecedor por OB + {formatNeMoney(result.financial.deductions ?? null)} em deduções/retenções por DR/DF.</p>}
      <p className="text-xs text-muted-foreground">Última atualização: {new Date(result.updatedAt).toLocaleString("pt-BR")}. Ausência de valor não confirma ausência de liquidação ou pagamento.</p>
      {(result.financial.paymentIncomplete || result.financial.liquidationIncomplete) && <p role="status" className="rounded border border-amber-400 p-3 text-sm">O SAGEP encontrou e somou os valores já comprovados, mas ainda há {result.financial.unresolvedPayments ?? 0} documento(s) de pagamento e {result.financial.unresolvedLiquidations ?? 0} documento(s) de liquidação sem parcela confirmada para esta NE. O total exibido é parcial e permanece a conferir.</p>}
      {result.financial.inconsistent && <p role="alert" className="rounded border border-amber-400 p-3 text-sm">Os valores apresentam divergência e não entram nos totais do painel. Confira os documentos da NE.</p>}
      {"invoices" in result && Array.isArray(result.invoices) && result.invoices.length > 0 && <section><h3 className="font-semibold">Notas fiscais vinculadas</h3><div className="mt-2 space-y-2">{result.invoices.map(invoice => <div key={invoice.id} className="rounded border p-3 text-sm"><div className="flex flex-wrap items-center justify-between gap-2"><p className="font-semibold">NF-e {invoice.number}{invoice.series ? ` · Série ${invoice.series}` : ""}</p><span className={invoice.conferenceStatus === "CONFERRED" ? "text-emerald-600" : invoice.conferenceStatus === "DIVERGENT" ? "text-destructive" : "text-amber-600"}>{invoice.conferenceStatus === "CONFERRED" ? "Conferida" : invoice.conferenceStatus === "DIVERGENT" ? "Divergente" : "Conferência pendente"}</span></div><p>{invoice.issuerName ?? invoice.supplierCnpj} · {formatNeMoney(invoice.grossAmount)} · {formatNeDate(invoice.issuedAt)}</p><p className="mt-1 text-xs text-muted-foreground">Origem: {invoice.source === "XML" ? "XML autorizado" : "Cadastro manual"}{invoice.itemCount ? ` · ${invoice.itemCount} item(ns)` : ""}{invoice.xmlChecksumSha256 ? ` · SHA-256 ${invoice.xmlChecksumSha256.slice(0, 16)}…` : ""}</p></div>)}</div></section>}
      {result.snapshot.financial?.documents.map(d => <section key={`${d.phase}:${d.code}`} className="rounded border p-3 text-sm"><h3 className="font-semibold">{d.phase === 2 ? "Liquidação" : "Pagamento"} · {d.code}</h3><p>Parcela desta NE: {formatNeMoney(d.amount)}</p>{d.error && <p className="text-amber-700">{d.error}</p>}{d.subitems.length > 0 && <details><summary className="cursor-pointer">Ver subitens que compõem o valor</summary><RawRecords value={d.subitems} /></details>}</section>)}
      {Object.entries({ "Nota de Empenho": result.snapshot.document, "Documentos relacionados": result.snapshot.related }).map(([title, value]) => <section key={title}><h3 className="font-semibold">{title}</h3><RawRecords value={value} /></section>)}
    </>}
  </DialogContent></Dialog>
}
function RawRecords({ value }: { value: unknown }) {
  const rows = Array.isArray(value) ? value : value ? [value] : []
  if (!rows.length) return <p className="py-2 text-sm text-muted-foreground">Nenhum documento disponível na cópia salva.</p>
  return <>{rows.map((row, i) => <dl key={i} className="my-2 rounded border p-3 text-sm">{Object.entries(row ?? {}).map(([key, val]) => <div className="grid grid-cols-2 gap-2 border-b py-1" key={key}><dt className="break-words text-muted-foreground">{key}</dt><dd className="break-words">{typeof val === "object" ? JSON.stringify(val) : String(val ?? "—")}</dd></div>)}</dl>)}</>
}
