import { useState } from "react"
import { useQuery } from "@tanstack/react-query"
import { Link } from "react-router"
import { api } from "@/lib/api"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
type Row = { externalCode: string; number: string; origin: string; supplierName: string; current: number | null; liquidated: number | null; paid: number | null; status: string; updatedAt: string; project: { id: string; projectCode: number; title: string } | null }
const money = (v: number | null) => v === null ? "Não informado" : v.toLocaleString("pt-BR", { style: "currency", currency: "BRL" })
export function UnifiedPortfolio() {
  const [search, setSearch] = useState("")
  const [page, setPage] = useState(1)
  const [pageSize, setPageSize] = useState(10)
  const query = useQuery({ queryKey: ["financial-execution", "portfolio"], queryFn: () => api.get<{ rows: Row[]; total: number; coverage: { committed: number; liquidated: number; paid: number }; totals: { committed: number; liquidated: number; paid: number; pending: number } }>("/financial-execution/portfolio") })
  const rows = (query.data?.rows ?? []).filter(r => `${r.number} ${r.supplierName} ${r.externalCode}`.toLowerCase().includes(search.toLowerCase()))
  return <div className="space-y-4">
    {query.isLoading && <p>Carregando carteira consolidada…</p>}{query.isError && <p role="alert">{query.error.message}</p>}
    {query.data && <><div className="grid gap-3 md:grid-cols-4">{[{ label: "Empenhado informado", value: money(query.data.coverage.committed ? query.data.totals.committed : null), helper: `${query.data.coverage.committed} de ${query.data.total} NEs com valor utilizável` }, { label: "Liquidado informado", value: money(query.data.coverage.liquidated ? query.data.totals.liquidated : null), helper: `${query.data.coverage.liquidated} de ${query.data.total} NEs com valor utilizável` }, { label: "Pago informado", value: money(query.data.coverage.paid ? query.data.totals.paid : null), helper: `${query.data.coverage.paid} de ${query.data.total} NEs com valor utilizável` }, { label: "NEs a conferir", value: String(query.data.totals.pending), helper: "Dados ausentes, não validados ou divergentes" }].map(c => <Card key={c.label}><CardHeader><CardTitle className="text-sm">{c.label}</CardTitle></CardHeader><CardContent className="text-2xl font-semibold">{c.value}<p className="mt-2 text-xs font-normal text-muted-foreground">{c.helper}</p></CardContent></Card>)}</div>
    <Card><CardHeader><CardTitle>Carteira consolidada · {query.data.total} NEs únicas</CardTitle><p className="text-sm text-muted-foreground">Projetos, importadas e avulsas. Cada código conta uma vez; o registro do projeto tem prioridade. Importações não consomem saldo de ATA.</p><p className="text-xs text-muted-foreground">Valores ausentes ficam como não informados. Registros com valores inconsistentes são sinalizados e excluídos dos totais até conferência.</p><Input placeholder="Buscar NE, fornecedor ou UG" value={search} onChange={e => { setSearch(e.target.value); setPage(1) }} /></CardHeader><CardContent><div className="overflow-auto"><table className="w-full text-sm"><thead><tr>{["NE / origem", "Fornecedor", "Empenhado", "Liquidado", "Pago", "Situação", "Atualização"].map(h => <th className="p-2 text-left" key={h}>{h}</th>)}</tr></thead><tbody>{rows.slice((page-1)*pageSize,page*pageSize).map(r => <tr key={r.externalCode} className="border-t"><td className="p-2"><strong>{r.number}</strong><p className="text-xs">UG {r.externalCode.slice(0,6)} · {r.origin === "PROJECT" ? "Projeto" : r.origin === "STANDALONE" ? "Avulsa" : "Importada"}</p>{r.project && <Link className="text-primary" to={`/projects/${r.project.id}`}>PRJ-{r.project.projectCode}</Link>}</td><td className="p-2">{r.supplierName}</td><td className="p-2">{money(r.current)}</td><td className="p-2">{money(r.liquidated)}</td><td className="p-2">{money(r.paid)}</td><td className="p-2">{r.status.replaceAll("_", " ")}</td><td className="p-2">{r.updatedAt ? new Date(r.updatedAt).toLocaleString("pt-BR") : "Não informada"}</td></tr>)}</tbody></table></div><div className="mt-4 flex items-center gap-3"><label>Itens <select value={pageSize} onChange={e => { setPageSize(Number(e.target.value)); setPage(1) }}>{[10,20,30,50].map(n=><option key={n}>{n}</option>)}</select></label><Button variant="outline" disabled={page === 1} onClick={() => setPage(p=>p-1)}>Anterior</Button><span>{page} / {Math.max(1,Math.ceil(rows.length/pageSize))}</span><Button variant="outline" disabled={page*pageSize>=rows.length} onClick={()=>setPage(p=>p+1)}>Próxima</Button></div></CardContent></Card></>}
  </div>
}
