import { useState } from "react"
import { Boxes, Loader2 } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { Textarea } from "@/components/ui/textarea"
import type { Ata, AtaItem, AtaItemPayload } from "@/features/atas/atas.types"

type Props = { open: boolean; onOpenChange: (open: boolean) => void; ata: Ata; item?: AtaItem | null; pending: boolean; onSubmit: (payload: AtaItemPayload) => Promise<void> }

export function AtaItemDialog({ open, onOpenChange, ata, item, pending, onSubmit }: Props) {
  const [groupCode, setGroupCode] = useState(item?.coverageGroup.code ?? ata.coverageGroups[0]?.code ?? ""); const [referenceCode, setReferenceCode] = useState(item?.referenceCode ?? ""); const [description, setDescription] = useState(item?.description ?? ""); const [unit, setUnit] = useState(item?.unit ?? "UN"); const [unitPrice, setUnitPrice] = useState(item?.unitPrice ?? ""); const [initialQuantity, setInitialQuantity] = useState(item?.initialQuantity ?? ""); const [notes, setNotes] = useState(item?.notes ?? ""); const [error, setError] = useState<string | null>(null)
  const submit = async () => { const price = Number(unitPrice.replace(",", ".")); const quantity = Number(initialQuantity.replace(",", ".")); if (!groupCode || !referenceCode.trim() || description.trim().length < 3 || !unit.trim() || price <= 0 || quantity <= 0) { setError("Preencha o grupo, referência, descrição, unidade, preço e saldo inicial com valores válidos."); return } await onSubmit({ coverageGroupCode: groupCode, referenceCode: referenceCode.trim(), description: description.trim(), unit: unit.trim().toUpperCase(), unitPrice: price, initialQuantity: quantity, ...(notes.trim() && { notes: notes.trim() }) }) }
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent><DialogHeader><DialogTitle className="flex items-center gap-2"><Boxes className="size-5 text-primary" />{item ? "Editar item da ATA" : "Novo item da ATA"}</DialogTitle><DialogDescription>Os saldos reservado, consumido e disponível serão calculados automaticamente a partir do saldo inicial.</DialogDescription></DialogHeader><div className="space-y-4"><div className="space-y-2"><Label>Grupo de cobertura</Label><Select value={groupCode} onValueChange={setGroupCode}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{ata.coverageGroups.map((group) => <SelectItem key={group.id} value={group.code}>{group.code} · {group.name}</SelectItem>)}</SelectContent></Select></div><div className="grid gap-4 sm:grid-cols-2"><div className="space-y-2"><Label>Referência</Label><Input value={referenceCode} onChange={(event) => setReferenceCode(event.target.value)} autoFocus /></div><div className="space-y-2"><Label>Unidade</Label><Input value={unit} onChange={(event) => setUnit(event.target.value)} /></div></div><div className="space-y-2"><Label>Descrição</Label><Textarea value={description} onChange={(event) => setDescription(event.target.value)} rows={3} /></div><div className="grid gap-4 sm:grid-cols-2"><div className="space-y-2"><Label>Valor unitário (R$)</Label><Input inputMode="decimal" value={unitPrice} onChange={(event) => setUnitPrice(event.target.value)} /></div><div className="space-y-2"><Label>Saldo inicial</Label><Input inputMode="decimal" value={initialQuantity} onChange={(event) => setInitialQuantity(event.target.value)} /></div></div><div className="space-y-2"><Label>Observações</Label><Input value={notes} onChange={(event) => setNotes(event.target.value)} /></div>{error && <p className="text-sm font-medium text-destructive">{error}</p>}</div><DialogFooter><Button variant="outline" onClick={() => onOpenChange(false)} disabled={pending}>Cancelar</Button><Button onClick={submit} disabled={pending}>{pending && <Loader2 className="size-4 animate-spin" />}{item ? "Salvar item" : "Adicionar item"}</Button></DialogFooter></DialogContent></Dialog>
}
