import { useMemo, useState } from "react"
import { useMutation } from "@tanstack/react-query"
import { AlertTriangle, ArrowLeft, CheckCircle2, CloudDownload, Loader2, Search } from "lucide-react"
import { toast } from "sonner"
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table"
import { atasService } from "@/features/atas/atas.service"
import type { AtaType, ComprasGovImportResult, ComprasGovPreview } from "@/features/atas/atas.types"
import type { FederativeUnit } from "@/features/projects/projects.types"

type Props = { open: boolean; onOpenChange: (open: boolean) => void; onImported: (result: ComprasGovImportResult) => void }
function money(value: number) { return value.toLocaleString("pt-BR", { style: "currency", currency: "BRL" }) }
const currentYear = String(new Date().getFullYear())

export function ComprasGovImportDialog({ open, onOpenChange, onImported }: Props) {
  const [uasg, setUasg] = useState(""); const [numeroPregao, setNumeroPregao] = useState(""); const [anoPregao, setAnoPregao] = useState(currentYear); const [numeroAta, setNumeroAta] = useState(""); const [preview, setPreview] = useState<ComprasGovPreview | null>(null); const [ataType, setAtaType] = useState<AtaType>("CFTV"); const [groupCode, setGroupCode] = useState("MNS"); const [groupName, setGroupName] = useState("Grupo Manaus"); const [cityName, setCityName] = useState("Manaus"); const [stateUf, setStateUf] = useState<FederativeUnit>("AM")
  const canSearch = uasg.trim() && numeroPregao.trim() && /^\d{4}$/.test(anoPregao)
  const previewMutation = useMutation({ mutationFn: (selectedAta?: string) => atasService.previewComprasGov({ uasg: uasg.trim(), numeroPregao: numeroPregao.trim(), anoPregao, ...(selectedAta && { numeroAta: selectedAta }) }), onSuccess: (data) => { setPreview(data); if (data.ata) setNumeroAta(data.selectedAta?.ataNumber ?? numeroAta) }, onError: (error) => toast.error(error.message) })
  const importMutation = useMutation({ mutationFn: () => atasService.importComprasGov({ uasg: uasg.trim(), numeroPregao: numeroPregao.trim(), anoPregao, ...(numeroAta && { numeroAta }), ataType, coverageGroupCode: groupCode.trim().toUpperCase(), coverageGroupName: groupName.trim(), coverageGroupLocalities: [{ cityName: cityName.trim(), stateUf }] }), onSuccess: (result) => { toast.success(`${result.ata.number} importada: ${result.itemsCreated} item(ns) criado(s) e ${result.itemsUpdated} atualizado(s).`); onImported(result); onOpenChange(false) }, onError: (error) => toast.error(error.message) })
  const totalAmount = useMemo(() => preview?.items.reduce((sum, item) => sum + item.unitPrice * item.initialQuantity, 0) ?? 0, [preview])
  const resetPreview = () => { setPreview(null); setNumeroAta("") }

  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="max-h-[92vh] overflow-y-auto sm:max-w-4xl"><DialogHeader><DialogTitle className="flex items-center gap-2"><CloudDownload className="size-5 text-primary" />Importar ATA do Compras.gov.br</DialogTitle><DialogDescription>Consulte um pregão oficial, confira a ATA e importe seus dados, itens, quantidades e valores.</DialogDescription></DialogHeader>
    {!preview ? <div className="space-y-5"><div className="grid gap-4 sm:grid-cols-3"><div className="space-y-2"><Label>UASG</Label><Input value={uasg} onChange={(event) => setUasg(event.target.value)} placeholder="Ex.: 160016" autoFocus /></div><div className="space-y-2"><Label>Número do pregão</Label><Input value={numeroPregao} onChange={(event) => setNumeroPregao(event.target.value)} placeholder="Ex.: 90001" /></div><div className="space-y-2"><Label>Ano</Label><Input value={anoPregao} onChange={(event) => setAnoPregao(event.target.value.replace(/\D/g, "").slice(0, 4))} inputMode="numeric" /></div></div><Alert><Search /><AlertTitle>Consulta sem gravação</AlertTitle><AlertDescription>Nenhum dado será salvo até a confirmação final da importação.</AlertDescription></Alert></div> : preview.ata ? <div className="space-y-5"><div className="grid gap-4 rounded-xl border p-4 sm:grid-cols-4"><div><p className="text-xs text-muted-foreground">ATA</p><p className="mt-1 font-medium">{preview.ata.number}</p></div><div><p className="text-xs text-muted-foreground">Fornecedor</p><p className="mt-1 font-medium">{preview.ata.vendorName || "Não informado"}</p></div><div><p className="text-xs text-muted-foreground">Itens</p><p className="mt-1 font-medium">{preview.items.length}</p></div><div><p className="text-xs text-muted-foreground">Valor homologado</p><p className="mt-1 font-medium">{money(totalAmount)}</p></div></div>
      {preview.warnings.length > 0 && <Alert><AlertTriangle /><AlertTitle>Atenções da consulta</AlertTitle><AlertDescription><ul className="list-disc space-y-1 pl-4">{preview.warnings.map((warning) => <li key={warning}>{warning}</li>)}</ul></AlertDescription></Alert>}
      <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><div className="space-y-2"><Label>Tipo da ATA</Label><Select value={ataType} onValueChange={(value) => setAtaType(value as AtaType)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="CFTV">CFTV</SelectItem><SelectItem value="FIBRA_OPTICA">Fibra Óptica</SelectItem></SelectContent></Select></div><div className="space-y-2"><Label>Código do grupo</Label><Input value={groupCode} onChange={(event) => setGroupCode(event.target.value)} /></div><div className="space-y-2"><Label>Nome do grupo</Label><Input value={groupName} onChange={(event) => setGroupName(event.target.value)} /></div><div className="space-y-2"><Label>Localidade</Label><div className="flex gap-2"><Input value={cityName} onChange={(event) => setCityName(event.target.value)} /><Select value={stateUf} onValueChange={(value) => setStateUf(value as FederativeUnit)}><SelectTrigger className="w-24"><SelectValue /></SelectTrigger><SelectContent>{["AM", "RO", "RR", "AC"].map((uf) => <SelectItem key={uf} value={uf}>{uf}</SelectItem>)}</SelectContent></Select></div></div></div>
      <div className="max-h-72 overflow-auto rounded-xl border"><Table><TableHeader><TableRow><TableHead>Referência</TableHead><TableHead>Descrição</TableHead><TableHead>Unidade</TableHead><TableHead className="text-right">Quantidade</TableHead><TableHead className="text-right">Valor unitário</TableHead></TableRow></TableHeader><TableBody>{preview.items.map((item) => <TableRow key={`${item.externalItemId}-${item.referenceCode}`}><TableCell className="font-medium">{item.referenceCode}</TableCell><TableCell className="max-w-sm text-xs">{item.description}</TableCell><TableCell>{item.unit}</TableCell><TableCell className="text-right">{item.initialQuantity.toLocaleString("pt-BR")}</TableCell><TableCell className="text-right">{money(item.unitPrice)}</TableCell></TableRow>)}</TableBody></Table></div>
    </div> : <div className="space-y-4"><Alert><CheckCircle2 /><AlertTitle>{preview.atasFound.length} ATA(s) encontrada(s)</AlertTitle><AlertDescription>Selecione a ATA que deseja conferir e importar.</AlertDescription></Alert><div className="grid gap-3 sm:grid-cols-2">{preview.atasFound.map((found) => <button type="button" key={found.ataNumber} className="rounded-xl border p-4 text-left transition hover:border-primary hover:bg-primary/5" onClick={() => { setNumeroAta(found.ataNumber); previewMutation.mutate(found.ataNumber) }}><div className="flex items-center justify-between gap-2"><p className="font-medium">{found.ataNumber}</p><Badge variant="outline">{found.itemCount} itens</Badge></div><p className="mt-2 text-sm text-muted-foreground">{found.vendorName || "Fornecedor não informado"}</p>{found.totalAmount !== null && <p className="mt-3 font-medium">{money(found.totalAmount)}</p>}</button>)}</div></div>}
    <DialogFooter>{preview && <Button variant="ghost" onClick={resetPreview} disabled={previewMutation.isPending || importMutation.isPending}><ArrowLeft className="size-4" />Nova consulta</Button>}<Button variant="outline" onClick={() => onOpenChange(false)} disabled={previewMutation.isPending || importMutation.isPending}>Cancelar</Button>{!preview && <Button onClick={() => previewMutation.mutate(undefined)} disabled={!canSearch || previewMutation.isPending}>{previewMutation.isPending && <Loader2 className="size-4 animate-spin" />}Consultar pregão</Button>}{preview?.ata && <Button onClick={() => importMutation.mutate()} disabled={!preview.items.length || groupCode.trim().length < 2 || groupName.trim().length < 2 || cityName.trim().length < 2 || importMutation.isPending}>{importMutation.isPending && <Loader2 className="size-4 animate-spin" />}Importar ATA completa</Button>}</DialogFooter>
  </DialogContent></Dialog>
}
