import { useState } from "react"
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query"
import { Download, FileArchive, FileImage, FileText, Loader2, Plus, Trash2 } from "lucide-react"
import { toast } from "sonner"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { Textarea } from "@/components/ui/textarea"
import { evidencesService } from "../evidences.service"
import type { EvidenceCategory, EvidencePhase, ProjectEvidence } from "../evidences.types"

const categories: Record<EvidenceCategory, string> = { IMAGE: "Imagem", VIDEO: "Vídeo", KMZ_KML: "KMZ / KML", TECHNICAL_DOCUMENT: "Documento técnico", CERTIFICATION: "Certificação", DIAGRAM: "Diagrama", AS_BUILT: "As-Built", OTHER: "Outro" }
const phases: Record<EvidencePhase, string> = { BEFORE: "Antes", DURING: "Durante", AFTER: "Depois", GENERAL: "Geral" }
const size = (bytes: number) => bytes < 1024 * 1024 ? `${Math.ceil(bytes / 1024)} KB` : `${(bytes / 1024 / 1024).toFixed(1)} MB`
const categoryByExtension = (filename: string): EvidenceCategory => { const extension = filename.split(".").pop()?.toLowerCase(); if (["jpg", "jpeg", "png", "webp"].includes(extension ?? "")) return "IMAGE"; if (["mp4", "webm"].includes(extension ?? "")) return "VIDEO"; if (["kmz", "kml"].includes(extension ?? "")) return "KMZ_KML"; return "TECHNICAL_DOCUMENT" }

export function EvidencesPanel({ projectId, taskId, canManage }: { projectId: string; taskId?: string; canManage: boolean }) {
  const client = useQueryClient(); const [file, setFile] = useState<File | null>(null); const [title, setTitle] = useState(""); const [description, setDescription] = useState(""); const [category, setCategory] = useState<EvidenceCategory>("IMAGE"); const [phase, setPhase] = useState<EvidencePhase>("GENERAL"); const [include, setInclude] = useState(false)
  const query = useQuery({ queryKey: ["evidences", projectId], queryFn: () => evidencesService.list(projectId) })
  const visible = taskId ? query.data?.filter((item) => item.taskId === taskId) : query.data
  const refresh = () => client.invalidateQueries({ queryKey: ["evidences", projectId] })
  const upload = useMutation({ mutationFn: () => evidencesService.upload(file!, { projectId, taskId, title, description, category, phase, includeInReport: include }), onSuccess: () => { toast.success("Evidência adicionada ao projeto."); setFile(null); setTitle(""); setDescription(""); refresh() }, onError: (error) => toast.error(error.message) })
  const update = useMutation({ mutationFn: ({ id, includeInReport }: { id: string; includeInReport: boolean }) => evidencesService.update(id, { includeInReport }), onSuccess: refresh, onError: (error) => toast.error(error.message) })
  const remove = useMutation({ mutationFn: (id: string) => evidencesService.remove(id), onSuccess: () => { toast.success("Evidência removida."); refresh() }, onError: (error) => toast.error(error.message) })
  const open = async (item: ProjectEvidence) => { try { const blob = await evidencesService.content(item.id); const url = URL.createObjectURL(blob); window.open(url, "_blank", "noopener,noreferrer"); setTimeout(() => URL.revokeObjectURL(url), 60000) } catch (error) { toast.error(error instanceof Error ? error.message : "Falha ao abrir arquivo") } }
  return <div className="space-y-5">
    {canManage && <Card className="border-none shadow-sm"><CardHeader><CardTitle className="flex items-center gap-2"><Plus className="size-5 text-primary" />Adicionar arquivo ou evidência</CardTitle><CardDescription>Imagens, vídeos, KMZ/KML, certificações, diagramas e documentos técnicos. Limite de 100 MB.</CardDescription></CardHeader><CardContent className="grid gap-4 md:grid-cols-2"><div className="space-y-2 md:col-span-2"><Label htmlFor={`evidence-file-${taskId ?? "project"}`}>Arquivo</Label><Input id={`evidence-file-${taskId ?? "project"}`} type="file" accept=".jpg,.jpeg,.png,.webp,.mp4,.webm,.pdf,.kmz,.kml,.docx,.xlsx,.csv" onChange={(event) => { const selected = event.target.files?.[0] ?? null; setFile(selected); if (selected) { if (!title) setTitle(selected.name.replace(/\.[^.]+$/, "")); setCategory(categoryByExtension(selected.name)) } }} /></div><div className="space-y-2"><Label>Título</Label><Input value={title} onChange={(e) => setTitle(e.target.value)} /></div><div className="space-y-2"><Label>Categoria</Label><Select value={category} onValueChange={(v) => setCategory(v as EvidenceCategory)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{Object.entries(categories).map(([value,label]) => <SelectItem key={value} value={value}>{label}</SelectItem>)}</SelectContent></Select></div><div className="space-y-2"><Label>Fase</Label><Select value={phase} onValueChange={(v) => setPhase(v as EvidencePhase)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{Object.entries(phases).map(([value,label]) => <SelectItem key={value} value={value}>{label}</SelectItem>)}</SelectContent></Select></div><label className="flex items-center gap-3 self-end rounded-lg border p-3 text-sm"><input type="checkbox" checked={include} onChange={(e) => setInclude(e.target.checked)} />Incluir no relatório de entrega</label><div className="space-y-2 md:col-span-2"><Label>Legenda ou descrição</Label><Textarea value={description} onChange={(e) => setDescription(e.target.value)} placeholder="Local, equipamento, resultado do teste ou contexto da imagem" /></div><Button className="md:col-span-2 md:w-fit" disabled={!file || title.trim().length < 2 || upload.isPending} onClick={() => upload.mutate()}>{upload.isPending ? <Loader2 className="size-4 animate-spin" /> : <Plus className="size-4" />}Adicionar evidência</Button></CardContent></Card>}
    <Card className="border-none shadow-sm"><CardHeader><CardTitle>{taskId ? "Evidências desta tarefa" : "Arquivos e evidências do projeto"}</CardTitle><CardDescription>{visible?.length ?? 0} arquivo(s) registrado(s).</CardDescription></CardHeader><CardContent className="space-y-3">{query.isLoading ? <Loader2 className="size-5 animate-spin" /> : visible?.length ? visible.map((item) => <div key={item.id} className="flex flex-col justify-between gap-3 rounded-xl border p-4 sm:flex-row sm:items-center"><div className="flex min-w-0 gap-3">{item.category === "IMAGE" ? <FileImage className="mt-1 size-5 shrink-0 text-primary" /> : item.category === "KMZ_KML" ? <FileArchive className="mt-1 size-5 shrink-0 text-primary" /> : <FileText className="mt-1 size-5 shrink-0 text-primary" />}<div className="min-w-0"><p className="font-medium">{item.title}</p><p className="truncate text-sm text-muted-foreground">{item.originalName} · {size(item.sizeBytes)}</p>{item.description && <p className="mt-1 text-sm text-muted-foreground">{item.description}</p>}<div className="mt-2 flex flex-wrap gap-2"><Badge variant="outline">{categories[item.category]}</Badge><Badge variant="outline">{phases[item.phase]}</Badge>{item.task && <Badge variant="secondary">TSK-{item.task.taskCode}</Badge>}</div></div></div><div className="flex shrink-0 flex-wrap gap-2"><Button size="sm" variant="outline" onClick={() => open(item)}><Download className="size-4" />Abrir</Button>{canManage && <Button size="sm" variant={item.includeInReport ? "default" : "outline"} onClick={() => update.mutate({ id: item.id, includeInReport: !item.includeInReport })}>{item.includeInReport ? "No relatório" : "Incluir no relatório"}</Button>}{canManage && <Button size="icon-sm" variant="ghost" className="text-destructive" onClick={() => remove.mutate(item.id)} aria-label="Remover evidência"><Trash2 /></Button>}</div></div>) : <p className="py-10 text-center text-sm text-muted-foreground">Nenhuma evidência registrada.</p>}</CardContent></Card>
  </div>
}
