import { useState } from "react"
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query"
import { AlertTriangle, ArrowDownToLine, ArrowLeft, Boxes, CircleDollarSign, History, MapPin, Pencil, Plus, Power, RefreshCw, Search } from "lucide-react"
import { Link, useParams } from "react-router"
import { toast } from "sonner"
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Skeleton } from "@/components/ui/skeleton"
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table"
import { AtaDialog } from "@/features/atas/components/ata-dialog"
import { AtaItemDialog } from "@/features/atas/components/ata-item-dialog"
import { AtaItemMovementsDialog } from "@/features/atas/components/ata-item-movements-dialog"
import { ExternalConsumptionDialog } from "@/features/atas/components/external-consumption-dialog"
import { atasService } from "@/features/atas/atas.service"
import type { AtaItem, AtaItemPayload, AtaPayload, AtaUpdatePayload } from "@/features/atas/atas.types"

function formatCurrency(value: string | number) { return Number(value).toLocaleString("pt-BR", { style: "currency", currency: "BRL" }) }
function formatQuantity(value: string | number) { return Number(value).toLocaleString("pt-BR", { maximumFractionDigits: 2 }) }
function formatDate(value: string | null) { return value ? new Intl.DateTimeFormat("pt-BR", { dateStyle: "short" }).format(new Date(value)) : "Não informada" }

export function AtaDetailsPage() {
  const { ataId } = useParams<{ ataId: string }>(); const queryClient = useQueryClient(); const [search, setSearch] = useState(""); const [editOpen, setEditOpen] = useState(false); const [itemOpen, setItemOpen] = useState(false); const [selectedItem, setSelectedItem] = useState<AtaItem | null>(null); const [movementItem, setMovementItem] = useState<AtaItem | null>(null); const [externalConsumptionItem, setExternalConsumptionItem] = useState<AtaItem | null>(null)
  const ataQuery = useQuery({ queryKey: ["atas", "details", ataId], queryFn: () => atasService.details(ataId!), enabled: Boolean(ataId) })
  const itemsQuery = useQuery({ queryKey: ["atas", "items", ataId], queryFn: () => atasService.listItems(ataId!, { page: 1, pageSize: 100 }), enabled: Boolean(ataId) })
  const invalidate = () => { queryClient.invalidateQueries({ queryKey: ["atas"] }); queryClient.invalidateQueries({ queryKey: ["dashboard"] }) }
  const editMutation = useMutation({ mutationFn: (payload: AtaPayload | AtaUpdatePayload) => atasService.update(ataId!, payload as AtaUpdatePayload), onSuccess: () => { toast.success("ATA atualizada com sucesso."); setEditOpen(false); invalidate() }, onError: (error) => toast.error(error.message) })
  const itemMutation = useMutation({ mutationFn: (payload: AtaItemPayload) => selectedItem ? atasService.updateItem(selectedItem.id, payload) : atasService.createItem(ataId!, payload), onSuccess: (item) => { toast.success(`${item.referenceCode} ${selectedItem ? "atualizado" : "adicionado"} com sucesso.`); setItemOpen(false); setSelectedItem(null); invalidate() }, onError: (error) => toast.error(error.message) })
  const toggleItemMutation = useMutation({ mutationFn: (item: AtaItem) => atasService.updateItem(item.id, { isActive: !item.isActive }), onSuccess: (item) => { toast.success(`${item.referenceCode} ${item.isActive ? "ativado" : "inativado"}.`); invalidate() }, onError: (error) => toast.error(error.message) })

  if (ataQuery.isLoading) return <div className="space-y-4">{Array.from({ length: 5 }).map((_, index) => <Skeleton key={index} className="h-28" />)}</div>
  if (ataQuery.isError || !ataQuery.data) return <div className="space-y-4"><Button asChild variant="ghost"><Link to="/atas"><ArrowLeft className="size-4" />Voltar às ATAs</Link></Button><Alert variant="destructive"><AlertTriangle /><AlertTitle>Não foi possível carregar a ATA</AlertTitle><AlertDescription>{ataQuery.error?.message}</AlertDescription></Alert></div>
  const ata = ataQuery.data; const items = itemsQuery.data?.items ?? []; const normalizedSearch = search.trim().toLowerCase(); const filteredItems = items.filter((item) => !normalizedSearch || `${item.referenceCode} ${item.description} ${item.coverageGroup.code}`.toLowerCase().includes(normalizedSearch)); const totals = items.reduce((acc, item) => ({ initial: acc.initial + Number(item.balance.initialAmount), available: acc.available + Number(item.balance.availableAmount), reserved: acc.reserved + Number(item.balance.reservedAmount), consumed: acc.consumed + Number(item.balance.consumedAmount) }), { initial: 0, available: 0, reserved: 0, consumed: 0 }); const riskCount = items.filter((item) => item.balance.lowStock || item.balance.insufficient).length

  return <div className="space-y-6">
    <Button asChild variant="ghost" className="-ml-3"><Link to="/atas"><ArrowLeft className="size-4" />Voltar às ATAs</Link></Button>
    <Card className="border-none bg-sidebar text-sidebar-foreground shadow-sm"><CardContent className="p-6 lg:p-8"><div className="flex flex-col justify-between gap-5 lg:flex-row"><div><div className="flex flex-wrap gap-2"><Badge className="bg-sidebar-primary text-sidebar-primary-foreground">ATA-{ata.ataCode}</Badge><Badge variant="outline" className="border-white/20 text-white">{ata.type === "CFTV" ? "CFTV" : "Fibra Óptica / Ponto Lógico"}</Badge><Badge variant={ata.isActive ? "default" : "secondary"}>{ata.isActive ? "Ativa" : "Inativa"}</Badge></div><h1 className="mt-4 text-3xl font-semibold">{ata.number}</h1><p className="mt-2 text-sidebar-foreground/70">{ata.vendorName} · {ata.managingAgency || "Órgão gerenciador não informado"}</p><p className="mt-2 text-xs text-sidebar-foreground/60">Vigência: {formatDate(ata.validFrom)} até {formatDate(ata.validUntil)}</p></div><div className="flex flex-wrap items-start gap-2"><Button className="bg-sidebar-primary text-sidebar-primary-foreground" onClick={() => { setSelectedItem(null); setItemOpen(true) }} disabled={!ata.coverageGroups.length}><Plus className="size-4" />Novo item</Button><Button variant="secondary" onClick={() => setEditOpen(true)}><Pencil className="size-4" />Editar ATA</Button><Button variant="secondary" onClick={() => { ataQuery.refetch(); itemsQuery.refetch() }}><RefreshCw className="size-4" />Atualizar</Button></div></div>{ata.notes && <p className="mt-5 rounded-xl border border-white/10 bg-white/5 p-4 text-sm text-sidebar-foreground/70">{ata.notes}</p>}</CardContent></Card>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[{ label: "Valor inicial", value: totals.initial }, { label: "Saldo disponível", value: totals.available }, { label: "Valor reservado", value: totals.reserved }, { label: "Valor consumido", value: totals.consumed }].map((metric) => <Card key={metric.label} className="border-none shadow-sm"><CardContent className="flex items-center justify-between p-5"><div><p className="text-sm text-muted-foreground">{metric.label}</p><p className="mt-2 text-xl font-semibold">{formatCurrency(metric.value)}</p></div><CircleDollarSign className="size-5 text-primary" /></CardContent></Card>)}</div>
    <div className="grid gap-4 lg:grid-cols-2">{ata.coverageGroups.map((group) => <Card key={group.id} className="border-none shadow-sm"><CardHeader><CardTitle className="flex items-center gap-2"><MapPin className="size-5 text-primary" />{group.code} · {group.name}</CardTitle></CardHeader><CardContent><p className="text-sm text-muted-foreground">{group.description || "Sem descrição adicional."}</p><div className="mt-4 flex flex-wrap gap-2">{group.localities.map((locality) => <Badge key={`${locality.cityName}-${locality.stateUf}`} variant="outline">{locality.cityName}/{locality.stateUf}</Badge>)}</div></CardContent></Card>)}</div>
    <Card className="border-none shadow-sm"><CardHeader className="flex flex-row items-center justify-between gap-4"><div><CardTitle className="flex items-center gap-2"><Boxes className="size-5 text-primary" />Itens e saldos</CardTitle><p className="mt-2 text-sm text-muted-foreground">{items.length} item(ns) · {riskCount} com saldo crítico</p></div><div className="relative w-full max-w-xs"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" /><Input className="pl-9" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Buscar item..." /></div></CardHeader><CardContent className="overflow-x-auto">{itemsQuery.isLoading ? <div className="space-y-3">{Array.from({ length: 5 }).map((_, index) => <Skeleton key={index} className="h-14" />)}</div> : filteredItems.length ? <Table><TableHeader><TableRow><TableHead>Item</TableHead><TableHead>Grupo</TableHead><TableHead>Preço</TableHead><TableHead>Inicial</TableHead><TableHead>Reservado</TableHead><TableHead>Consumido</TableHead><TableHead>Disponível</TableHead><TableHead>Status</TableHead><TableHead className="text-right">Ações</TableHead></TableRow></TableHeader><TableBody>{filteredItems.map((item) => <TableRow key={item.id}><TableCell><p className="font-medium">{item.referenceCode}</p><p className="mt-1 max-w-64 text-xs text-muted-foreground">{item.description}</p></TableCell><TableCell><Badge variant="outline">{item.coverageGroup.code}</Badge></TableCell><TableCell>{formatCurrency(item.unitPrice)}</TableCell><TableCell>{formatQuantity(item.balance.initialQuantity)} {item.unit}</TableCell><TableCell>{formatQuantity(item.balance.reservedQuantity)}</TableCell><TableCell>{formatQuantity(item.balance.consumedQuantity)}</TableCell><TableCell className="font-medium">{formatQuantity(item.balance.availableQuantity)}</TableCell><TableCell>{item.balance.insufficient ? <Badge variant="destructive">Esgotado</Badge> : item.balance.lowStock ? <Badge variant="outline">Saldo baixo</Badge> : <Badge variant={item.isActive ? "default" : "secondary"}>{item.isActive ? "Disponível" : "Inativo"}</Badge>}</TableCell><TableCell><div className="flex justify-end gap-1"><Button variant="ghost" size="icon" title="Editar" onClick={() => { setSelectedItem(item); setItemOpen(true) }}><Pencil className="size-4" /></Button><Button variant="ghost" size="icon" title={item.isActive ? "Inativar" : "Ativar"} onClick={() => toggleItemMutation.mutate(item)}><Power className={item.isActive ? "size-4 text-destructive" : "size-4 text-primary"} /></Button></div></TableCell></TableRow>)}</TableBody></Table> : <div className="py-14 text-center"><Boxes className="mx-auto size-10 text-muted-foreground" /><p className="mt-4 font-medium">Nenhum item encontrado</p></div>}</CardContent></Card>
    {items.length > 0 && <Card className="border-none shadow-sm"><CardHeader><CardTitle className="flex items-center gap-2"><History className="size-5 text-primary" />Rastreabilidade dos saldos</CardTitle></CardHeader><CardContent className="grid gap-3 md:grid-cols-2">{items.map((item) => <div key={item.id} className="flex items-center justify-between gap-3 rounded-xl border p-3"><div className="min-w-0"><p className="truncate text-sm font-medium">{item.referenceCode} · {item.description}</p><p className="mt-1 text-xs text-muted-foreground">Disponível: {formatQuantity(item.balance.availableQuantity)} {item.unit}</p></div><div className="flex shrink-0 gap-1"><Button variant="outline" size="sm" onClick={() => setMovementItem(item)}><History className="size-4" />Histórico</Button><Button variant="outline" size="sm" disabled={!item.isActive || Number(item.balance.availableQuantity) <= 0} onClick={() => setExternalConsumptionItem(item)}><ArrowDownToLine className="size-4" />Consumo externo</Button></div></div>)}</CardContent></Card>}
    {editOpen && <AtaDialog open={editOpen} onOpenChange={setEditOpen} ata={ata} pending={editMutation.isPending} onSubmit={async (payload) => { await editMutation.mutateAsync(payload) }} />}
    {itemOpen && <AtaItemDialog open={itemOpen} onOpenChange={(open) => { setItemOpen(open); if (!open) setSelectedItem(null) }} ata={ata} item={selectedItem} pending={itemMutation.isPending} onSubmit={async (payload) => { await itemMutation.mutateAsync(payload) }} />}
    {movementItem && <AtaItemMovementsDialog item={movementItem} open={Boolean(movementItem)} onOpenChange={(open) => !open && setMovementItem(null)} />}
    {externalConsumptionItem && <ExternalConsumptionDialog item={externalConsumptionItem} open={Boolean(externalConsumptionItem)} onOpenChange={(open) => !open && setExternalConsumptionItem(null)} onSaved={() => { invalidate(); queryClient.invalidateQueries({ queryKey: ["ata-items", externalConsumptionItem.id, "movements"] }) }} />}
  </div>
}
