import { useEffect, useMemo, useState } from "react"
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query"
import { AlertTriangle, ArrowUpRight, ChevronLeft, ChevronRight, FileStack, Pencil, Plus, Power, RefreshCw, Search, X } from "lucide-react"
import { Link } from "react-router"
import { toast } from "sonner"
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog"
import { Input } from "@/components/ui/input"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { Skeleton } from "@/components/ui/skeleton"
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table"
import { AtaDialog } from "@/features/atas/components/ata-dialog"
import { atasService } from "@/features/atas/atas.service"
import type { Ata, AtaPayload, AtaType, AtaUpdatePayload } from "@/features/atas/atas.types"
import type { FederativeUnit } from "@/features/projects/projects.types"

const typeLabels: Record<AtaType, string> = { CFTV: "CFTV", FIBRA_OPTICA: "Fibra Óptica / Ponto Lógico" }

function formatDate(value: string | null) { return value ? new Intl.DateTimeFormat("pt-BR", { dateStyle: "short" }).format(new Date(value)) : "Não informada" }

export function AtasPage() {
  const queryClient = useQueryClient(); const [search, setSearch] = useState(""); const [debouncedSearch, setDebouncedSearch] = useState(""); const [type, setType] = useState<AtaType | "all">("all"); const [stateUf, setStateUf] = useState<FederativeUnit | "all">("all"); const [activity, setActivity] = useState<"all" | "active" | "inactive">("all"); const [page, setPage] = useState(1); const [formOpen, setFormOpen] = useState(false); const [selected, setSelected] = useState<Ata | null>(null); const [toggleTarget, setToggleTarget] = useState<Ata | null>(null); const [referenceTime] = useState(() => Date.now())
  useEffect(() => { const timeout = window.setTimeout(() => { setDebouncedSearch(search.trim()); setPage(1) }, 350); return () => window.clearTimeout(timeout) }, [search])
  const filters = useMemo(() => ({ page, pageSize: 10, search: debouncedSearch || undefined, type: type === "all" ? undefined : type, stateUf: stateUf === "all" ? undefined : stateUf, active: activity === "all" ? undefined : activity === "active" }), [activity, debouncedSearch, page, stateUf, type])
  const query = useQuery({ queryKey: ["atas", "list", filters], queryFn: () => atasService.list(filters), placeholderData: (previous) => previous })
  const summaryQuery = useQuery({ queryKey: ["atas", "summary"], queryFn: () => atasService.list({ page: 1, pageSize: 100 }) })
  const invalidate = () => queryClient.invalidateQueries({ queryKey: ["atas"] })
  const saveMutation = useMutation({ mutationFn: (payload: AtaPayload | AtaUpdatePayload) => selected ? atasService.update(selected.id, payload as AtaUpdatePayload) : atasService.create(payload as AtaPayload), onSuccess: (ata) => { toast.success(`${ata.number} ${selected ? "atualizada" : "cadastrada"} com sucesso.`); setFormOpen(false); setSelected(null); invalidate() }, onError: (error) => toast.error(error.message) })
  const toggleMutation = useMutation({ mutationFn: (ata: Ata) => atasService.update(ata.id, { isActive: !ata.isActive }), onSuccess: (ata) => { toast.success(`${ata.number} ${ata.isActive ? "ativada" : "inativada"}.`); setToggleTarget(null); invalidate() }, onError: (error) => toast.error(error.message) })
  const allAtas = summaryQuery.data?.items ?? []; const activeCount = allAtas.filter((ata) => ata.isActive).length; const expiringCount = allAtas.filter((ata) => ata.validUntil && new Date(ata.validUntil).getTime() >= referenceTime && new Date(ata.validUntil).getTime() <= referenceTime + 90 * 86400000).length; const hasFilters = Boolean(search || type !== "all" || stateUf !== "all" || activity !== "all"); const meta = query.data?.meta
  const clearFilters = () => { setSearch(""); setDebouncedSearch(""); setType("all"); setStateUf("all"); setActivity("all"); setPage(1) }
  return <div className="space-y-6">
    <div className="flex flex-col justify-between gap-4 lg:flex-row lg:items-end"><div><Badge className="mb-3">Contratações e saldos</Badge><h1 className="text-3xl font-semibold tracking-tight">ATAs</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-muted-foreground">Administre atas, cobertura territorial, vigência, itens precificados e disponibilidade para novos projetos.</p></div><div className="flex gap-2"><Button variant="outline" onClick={() => { query.refetch(); summaryQuery.refetch() }} disabled={query.isFetching}><RefreshCw className={query.isFetching ? "size-4 animate-spin" : "size-4"} />Atualizar</Button><Button onClick={() => { setSelected(null); setFormOpen(true) }}><Plus className="size-4" />Nova ATA</Button></div></div>
    <div className="grid gap-4 sm:grid-cols-3"><Card className="border-none shadow-sm"><CardContent className="p-5"><p className="text-sm text-muted-foreground">ATAs cadastradas</p><p className="mt-2 text-2xl font-semibold">{summaryQuery.isLoading ? "—" : allAtas.length}</p></CardContent></Card><Card className="border-none shadow-sm"><CardContent className="p-5"><p className="text-sm text-muted-foreground">ATAs ativas</p><p className="mt-2 text-2xl font-semibold">{summaryQuery.isLoading ? "—" : activeCount}</p></CardContent></Card><Card className="border-none shadow-sm"><CardContent className="p-5"><p className="text-sm text-muted-foreground">Vencem em até 90 dias</p><p className="mt-2 text-2xl font-semibold">{summaryQuery.isLoading ? "—" : expiringCount}</p></CardContent></Card></div>
    <Card className="border-none shadow-sm"><CardContent className="grid gap-3 p-5 md:grid-cols-2 xl:grid-cols-[minmax(260px,1fr)_200px_170px_200px_auto]"><div className="relative"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" /><Input className="pl-9" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Número, fornecedor ou órgão..." /></div><Select value={type} onValueChange={(value) => { setType(value as AtaType | "all"); setPage(1) }}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="all">Todos os tipos</SelectItem><SelectItem value="CFTV">CFTV</SelectItem><SelectItem value="FIBRA_OPTICA">Fibra Óptica</SelectItem></SelectContent></Select><Select value={stateUf} onValueChange={(value) => { setStateUf(value as FederativeUnit | "all"); setPage(1) }}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="all">Todos os estados</SelectItem>{["AM", "RO", "RR", "AC"].map((uf) => <SelectItem key={uf} value={uf}>{uf}</SelectItem>)}</SelectContent></Select><Select value={activity} onValueChange={(value) => { setActivity(value as "all" | "active" | "inactive"); setPage(1) }}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="all">Ativas e inativas</SelectItem><SelectItem value="active">Somente ativas</SelectItem><SelectItem value="inactive">Somente inativas</SelectItem></SelectContent></Select>{hasFilters && <Button variant="ghost" onClick={clearFilters}><X className="size-4" />Limpar</Button>}</CardContent></Card>
    {query.isError && <Alert variant="destructive"><AlertTriangle /><AlertTitle>Não foi possível carregar as ATAs</AlertTitle><AlertDescription>{query.error.message}</AlertDescription></Alert>}
    <Card className="border-none shadow-sm"><CardHeader className="flex flex-row items-center justify-between"><CardTitle className="flex items-center gap-2"><FileStack className="size-5 text-primary" />Catálogo de ATAs</CardTitle>{meta && <Badge variant="outline">{meta.totalItems} registro(s)</Badge>}</CardHeader><CardContent className="overflow-x-auto">{query.isLoading ? <div className="space-y-3">{Array.from({ length: 5 }).map((_, index) => <Skeleton key={index} className="h-16" />)}</div> : query.data?.items.length ? <Table><TableHeader><TableRow><TableHead>ATA</TableHead><TableHead>Fornecedor</TableHead><TableHead>Cobertura</TableHead><TableHead>Vigência</TableHead><TableHead>Status</TableHead><TableHead className="text-right">Ações</TableHead></TableRow></TableHeader><TableBody>{query.data.items.map((ata) => <TableRow key={ata.id}><TableCell><p className="font-medium">ATA-{ata.ataCode} · {ata.number}</p><p className="mt-1 text-xs text-primary">{typeLabels[ata.type]}</p></TableCell><TableCell><p className="font-medium">{ata.vendorName}</p><p className="mt-1 text-xs text-muted-foreground">{ata.managingAgency || "Órgão não informado"}</p></TableCell><TableCell><p>{ata.coverageGroups.length} grupo(s)</p><p className="mt-1 text-xs text-muted-foreground">{new Set(ata.coverageGroups.flatMap((group) => group.localities.map((locality) => locality.stateUf))).size} estado(s)</p></TableCell><TableCell><p className="text-sm">{formatDate(ata.validFrom)}</p><p className="mt-1 text-xs text-muted-foreground">até {formatDate(ata.validUntil)}</p></TableCell><TableCell><Badge variant={ata.isActive ? "default" : "secondary"}>{ata.isActive ? "Ativa" : "Inativa"}</Badge></TableCell><TableCell><div className="flex justify-end gap-1"><Button asChild variant="ghost" size="sm"><Link to={`/atas/${ata.id}`}>Abrir<ArrowUpRight className="size-4" /></Link></Button><Button variant="ghost" size="icon" onClick={() => { setSelected(ata); setFormOpen(true) }} title="Editar"><Pencil className="size-4" /></Button><Button variant="ghost" size="icon" onClick={() => setToggleTarget(ata)} title={ata.isActive ? "Inativar" : "Ativar"}><Power className={ata.isActive ? "size-4 text-destructive" : "size-4 text-primary"} /></Button></div></TableCell></TableRow>)}</TableBody></Table> : <div className="py-16 text-center"><FileStack className="mx-auto size-10 text-muted-foreground" /><p className="mt-4 font-medium">Nenhuma ATA encontrada</p></div>}{meta && meta.totalItems > 0 && <div className="mt-6 flex items-center justify-end gap-3 border-t pt-4"><span className="text-sm text-muted-foreground">Página {meta.page} de {meta.totalPages}</span><Button variant="outline" size="icon" disabled={!meta.hasPreviousPage} onClick={() => setPage((value) => value - 1)}><ChevronLeft className="size-4" /></Button><Button variant="outline" size="icon" disabled={!meta.hasNextPage} onClick={() => setPage((value) => value + 1)}><ChevronRight className="size-4" /></Button></div>}</CardContent></Card>
    {formOpen && <AtaDialog open={formOpen} onOpenChange={(open) => { setFormOpen(open); if (!open) setSelected(null) }} ata={selected} pending={saveMutation.isPending} onSubmit={async (payload) => { await saveMutation.mutateAsync(payload) }} />}
    <Dialog open={Boolean(toggleTarget)} onOpenChange={(open) => !open && setToggleTarget(null)}><DialogContent><DialogHeader><DialogTitle>{toggleTarget?.isActive ? "Inativar" : "Ativar"} ATA?</DialogTitle><DialogDescription>{toggleTarget?.isActive ? `${toggleTarget.number} deixará de ser oferecida em novas estimativas. Os vínculos existentes serão preservados.` : `${toggleTarget?.number} voltará a ficar disponível para uso.`}</DialogDescription></DialogHeader><DialogFooter><Button variant="outline" onClick={() => setToggleTarget(null)}>Cancelar</Button><Button variant={toggleTarget?.isActive ? "destructive" : "default"} onClick={() => toggleTarget && toggleMutation.mutate(toggleTarget)}>{toggleTarget?.isActive ? "Confirmar inativação" : "Confirmar ativação"}</Button></DialogFooter></DialogContent></Dialog>
  </div>
}
